# Generated by Django 5.1.4 on 2025-09-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('wave_type', models.CharField(choices=[('sine', 'Sine Wave'), ('square', 'Square Wave'), ('triangle', 'Triangle Wave'), ('sawtooth', 'Sawtooth Wave'), ('uploaded', 'Uploaded File')], default='uploaded', max_length=20)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='audio/original/')),
                ('modified_file', models.FileField(blank=True, null=True, upload_to='audio/modified/')),
                ('wave_parameters', models.JSONField(blank=True, default=dict)),
                ('envelope_data', models.JSONField(blank=True, default=dict)),
                ('background_color', models.CharField(default='#000000', max_length=7)),
                ('positive_color', models.CharField(default='#00FF00', max_length=7)),
                ('negative_color', models.CharField(default='#00FFFF', max_length=7)),
                ('final_drawing', models.ImageField(blank=True, null=True, upload_to='visualizations/final/')),
                ('final_drawing_svg', models.FileField(blank=True, null=True, upload_to='visualizations/final_svg/')),
                ('natural_lang', models.ImageField(blank=True, null=True, upload_to='visualizations/natural/')),
                ('natural_lang_svg', models.FileField(blank=True, null=True, upload_to='visualizations/natural_svg/')),
                ('wave_comparison', models.ImageField(blank=True, null=True, upload_to='visualizations/comparison/')),
                ('wave_comparison_svg', models.FileField(blank=True, null=True, upload_to='visualizations/comparison_svg/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_processing', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
